on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive
      
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install packages
        working-directory: ./
        run: yarn install --ignore-engines
      
      - name: Copy config.yml
        continue-on-error: true
        run: mv .\config.yml .\charticulator\config.yml
      # - name: Build charticulator
      #   env:
      #     NODE_OPTIONS: "--max-old-space-size=8192"
      #   working-directory: ./charticulator
      #   run: yarn build

      # - name: Build charticulator visual
      #   env:
      #     NODE_OPTIONS: "--max-old-space-size=8192"
      #   working-directory: ./visual
      #   run: yarn build

      - name: Build Charticulator
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        working-directory: ./
        run: yarn build:charticulator

      - name: Build visuals
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        working-directory: ./
        run: yarn build:visuals

      - name: Publish *.pbiviz
        uses: actions/upload-artifact@v4
        with:
          name: visual
          path: dist
